# Generated by Django 4.1.7 on 2023-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seal",
            name="seal_page",
            field=models.CharField(max_length=500, verbose_name="印章位置"),
        ),
    ]
