# Generated by Django 4.1.7 on 2023-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_main_person_project_tianyancha_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('title', models.CharField(max_length=100, verbose_name='文件名')),
                ('path', models.FileField(upload_to='static/file', verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'upload_file',
            },
        ),
    ]
