# Generated by Django 4.1.7 on 2023-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_uploadprojectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadprojectfile',
            name='path',
            field=models.FileField(upload_to='file', verbose_name='文件路径'),
        ),
        migrations.AlterModelTable(
            name='uploadprojectfile',
            table='upload_project_file',
        ),
    ]
