# Generated by Django 4.1.7 on 2023-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_uploadprojectfile_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadprojectfile',
            name='path',
            field=models.FileField(upload_to='project_file', verbose_name='文件路径'),
        ),
    ]
