# Generated by Django 4.1.7 on 2023-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_alter_uploadprojectfile_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('title', models.CharField(max_length=100, verbose_name='文件名')),
                ('path', models.FileField(upload_to='file/project_file', verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '上传检查文件',
                'verbose_name_plural': '上传检查文件',
                'db_table': 'upload_test_file',
            },
        ),
        migrations.AddField(
            model_name='uploadprojectfile',
            name='type',
            field=models.CharField(default=1, max_length=100, verbose_name='文件类型'),
            preserve_default=False,
        ),
    ]
