# Generated by Django 4.1.7 on 2023-03-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_uploadtestfile_uploadprojectfile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtestfile',
            name='path',
            field=models.FileField(upload_to='file/test_file', verbose_name='文件路径'),
        ),
    ]
