# Generated by Django 4.1.7 on 2023-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('APP', '0010_seal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGW_inquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=80, unique=True, verbose_name='公司名称')),
                ('penalty', models.CharField(max_length=200, verbose_name='处罚结果')),
            ],
            options={
                'verbose_name': '采购网',
                'verbose_name_plural': '采购网',
                'db_table': 'cgw_inquire',
            },
        ),
        migrations.CreateModel(
            name='Wenshuwang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80, unique=True, verbose_name='公司名称')),
                ('screen_shot',
                 models.ImageField(blank=True, null=True, upload_to='Media/wenshuwang_pic', verbose_name='截图')),
            ],
            options={
                'verbose_name': '文书网',
                'verbose_name_plural': '文书网',
                'db_table': 'wenshuwang_info',
            },
        ),
        migrations.CreateModel(
            name='Wenshuwang_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneW', models.CharField(max_length=80, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=80, verbose_name='密码')),
            ],
            options={
                'verbose_name': '文书网用户',
                'verbose_name_plural': '文书网用户',
                'db_table': 'wenshuwang_user_info',
            },
        ),
        migrations.AlterField(
            model_name='seal',
            name='path',
            field=models.FileField(upload_to='Media/Seal_Picture', verbose_name='印章路径'),
        ),
        migrations.AlterField(
            model_name='uploadprojectfile',
            name='path',
            field=models.FileField(upload_to='Media/file/project_file', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='uploadtestfile',
            name='path',
            field=models.FileField(upload_to='Media/file/test_file', verbose_name='文件路径'),
        ),
    ]
