# Generated by Django 4.1.7 on 2023-03-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('APP', '0011_cgw_inquire_wenshuwang_wenshuwang_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='path',
            field=models.FileField(upload_to='Seal_Picture', verbose_name='印章路径'),
        ),
        migrations.AlterField(
            model_name='uploadprojectfile',
            name='path',
            field=models.FileField(upload_to='file/project_file', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='uploadtestfile',
            name='path',
            field=models.FileField(upload_to='file/test_file', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='wenshuwang',
            name='screen_shot',
            field=models.ImageField(blank=True, null=True, upload_to='wenshuwang_pic', verbose_name='截图'),
        ),
    ]
