# Generated by Django 4.1.7 on 2023-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_shareholder_information_main_person_company_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shareholder_Information',
            new_name='Stocker',
        ),
    ]
