# Generated by Django 4.1.7 on 2023-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('APP', '0015_rename_stocker_shareholder_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='default_value', max_length=80, verbose_name='企业名称')),
                ('qualification_name', models.CharField(max_length=80, verbose_name='资质名称')),
                ('qualification_number', models.CharField(max_length=80, verbose_name='资质证书号')),
                ('qualification_type', models.CharField(max_length=80, verbose_name='资质类别')),
                ('qualification_date', models.CharField(max_length=80, verbose_name='发证日期')),
                ('qualification_validity', models.CharField(max_length=80, verbose_name='证书有效期')),
                ('qualification_authority', models.CharField(max_length=80, verbose_name='发证机关')),
            ],
            options={
                'verbose_name': '资质',
                'verbose_name_plural': '资质',
                'db_table': 'qualification',
            },
        ),
        migrations.RenameField(
            model_name='cgw_inquire',
            old_name='companyName',
            new_name='company_name',
        ),
    ]
