# Generated by Django 4.1.7 on 2023-03-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='default_value', max_length=80, verbose_name='企业名称')),
                ('register_person_name', models.CharField(max_length=80, verbose_name='姓名')),
                ('register_person_type', models.CharField(max_length=80, verbose_name='注册类别')),
                ('register_person_number', models.CharField(max_length=80, verbose_name='注册号')),
                ('register_person_profession', models.CharField(max_length=80, verbose_name='注册专业')),
            ],
            options={
                'verbose_name': '注册人员',
                'verbose_name_plural': '注册人员',
                'db_table': 'register_person',
            },
        ),
    ]
